version: "3.8"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api
        restart: on-failure
        depends_on:
            - db
        tty: true
        ports:
            - 3030:3030

    db:
        container_name: db
        image: mysql:5.7
        restart: always
        tty: true
        command: --default-authentication-plugin=mysql_native_password
        environment:
            TZ: Asia/Jakarta
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./repository/mysql/todos.sql:/docker-entrypoint-initdb.d/init.sql
